import { CATEGORY_LABELS } from "./category-labels";
import { formatCategoryScore } from "./format-category-score";
import { ChecksResponse } from "./types";

/** Client-side only, no server round-trip, no heavy dependency. */
export function buildMarkdownReport(results: ChecksResponse): string {
  const lines: string[] = [];

  lines.push(`# InfraLens report — ${results.hostname}`);
  lines.push("");
  lines.push(`- URL: ${results.url}`);
  lines.push(`- Analyzed: ${new Date(results.analyzedAt).toISOString()}`);
  lines.push(`- Score: ${results.score.score}/100 (${results.score.grade})`);
  lines.push(`- Duration: ${results.totalDurationMs}ms`);
  lines.push("");

  for (const category of results.score.categories) {
    const checks = results.checks.filter(
      (c) => c.category === category.category,
    );
    if (checks.length === 0) continue;

    lines.push(
      `## ${CATEGORY_LABELS[category.category] ?? category.category} — ${formatCategoryScore(category.score, category.maxScore)}`,
    );
    lines.push("");

    for (const check of checks) {
      lines.push(`### ${check.label} — ${check.status}`);
      if (check.summary) lines.push(check.summary);
      if (check.recommendation) {
        lines.push("");
        lines.push(`**Recommendation:** ${check.recommendation.title}`);
        lines.push(check.recommendation.description);
      }
      lines.push("");
    }
  }

  lines.push(
    "---",
    "Generated by InfraLens — a snapshot of public, automatically checkable signals, not a complete security or quality assessment.",
  );

  return lines.join("\n");
}

export function downloadTextFile(
  content: string,
  filename: string,
  mimeType: string,
) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();

  URL.revokeObjectURL(url);
}
