import { InfraLensExport } from "../checks/export";
import { CheckTransition, ComparisonResult } from "./diff";

/** Client-side only, same pattern as the single-report Markdown export (master plan §32 Phase 16 "export Markdown"). */
export function buildComparisonMarkdown(
  before: InfraLensExport,
  after: InfraLensExport,
  result: ComparisonResult,
): string {
  const lines: string[] = [];

  lines.push("# InfraLens comparison");
  lines.push("");
  lines.push(
    `- Report A: ${result.urlBefore} — ${result.scoreBefore}/100 (${result.gradeBefore}), scanned ${new Date(result.scannedAtBefore).toISOString()}`,
  );
  lines.push(
    `- Report B: ${result.urlAfter} — ${result.scoreAfter}/100 (${result.gradeAfter}), scanned ${new Date(result.scannedAtAfter).toISOString()}`,
  );
  lines.push(
    `- Score change: ${result.scoreDelta >= 0 ? "+" : ""}${result.scoreDelta}`,
  );
  lines.push("");

  lines.push("## Category scores");
  lines.push("");
  lines.push("| Category | A | B | Change |");
  lines.push("| --- | --- | --- | --- |");
  for (const c of result.categories) {
    lines.push(
      `| ${c.label} | ${c.before}/${c.beforeMax} | ${c.after}/${c.afterMax} | ${c.delta >= 0 ? "+" : ""}${c.delta} |`,
    );
  }
  lines.push("");

  const byKind = (kind: CheckTransition["kind"]) =>
    result.checks.filter((c) => c.kind === kind);

  const section = (title: string, items: CheckTransition[]) => {
    if (items.length === 0) return;
    lines.push(`## ${title}`);
    lines.push("");
    for (const item of items) {
      lines.push(
        `- **${item.label}**: ${item.before ?? "—"} → ${item.after ?? "—"}`,
      );
    }
    lines.push("");
  };

  section("Improvements", byKind("improved"));
  section("Regressions", byKind("regressed"));
  section("Other changes", byKind("changed"));
  section("New checks in B", byKind("added"));
  section("No longer present in B", byKind("removed"));

  lines.push("---");
  lines.push(
    "Generated by InfraLens — a snapshot of public, automatically checkable signals, not a complete security or quality assessment.",
  );

  return lines.join("\n");
}
